# Generated by Django 5.1.6 on 2025-02-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_migrate_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
    ]
