name: CI/CD Pipeline test for Development

on:
  push:
    branches:
      - develop_OC_Structure_pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Lint code
      run: flake8 .

    - name: Run tests
      run: pytest

    - name: Build Docker image
      run: |
        docker build -t my-app .
        docker run -d -p 8000:8000 my-app
